apiVersion: v1
kind: Service

metadata:
  name: mysql-service

spec:
  ports:
  - name: 3306-3306
    port: 3306
    protocol: TCP
    targetPort: mysql-port
  selector:
    app: mysql
  type: ClusterIP
