{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "f16jv.serviceAccountName" . }}
  labels:
{{ include "f16jv.labels" . | indent 4 }}
{{- end -}}
